version: "3.9"

services:
  users:
    image: "users-service"
    hostname: "users"
    ports:
      - "8000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      AppConfigurationConnectionString: ""
    build:
      context: .
      dockerfile: src/SiGameReborn.User.Api/Dockerfile
  tokens:
      image: "tokens-service"
      hostname: "tokens"
      ports:
        - "8001:80"
      environment:
        ASPNETCORE_ENVIRONMENT: "Development"
        AppConfigurationConnectionString: ""
      build:
        context: .
        dockerfile: src/SiGameReborn.Tokens.Api/Dockerfile
  registration:
    image: "registration-service"
    hostname: "registration"
    ports:
      - "8002:80"
    depends_on:
      - "users"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    build:
      context: .
      dockerfile: src/SiGameReborn.Registration.Api/Dockerfile
